2019-11-05 09:53:01,258 | A connection was made | 127.0.0.1 | 1144

2019-11-05 09:53:05,436 | Read | 127.0.0.1 | 1144
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-11-05 09:53:05,436 | Read | 127.0.0.1 | 1144
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-11-05 09:54:45,168 | A connection was made | 127.0.0.1 | 1524

2019-11-05 09:54:47,998 | Read | 127.0.0.1 | 1524
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-11-05 09:54:47,998 | Read | 127.0.0.1 | 1524
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-12-05 11:22:37,269 | A connection was made | 127.0.0.1 | 2012

2019-12-05 11:24:23,721 | A connection was made | 127.0.0.1 | 1944

2019-12-05 11:24:26,721 | Read | 127.0.0.1 | 1944
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-12-05 11:24:26,721 | Read | 127.0.0.1 | 1944
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-12-05 11:24:29,337 | Read | 127.0.0.1 | 2012
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-12-05 11:24:29,337 | Read | 127.0.0.1 | 2012
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2019-12-05 11:24:29,337 | Read | 127.0.0.1 | 2012
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2020-01-04 20:39:44,660 | A connection was made | 127.0.0.1 | 1424

2020-01-04 20:39:45,209 | Read | 127.0.0.1 | 1424
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

2020-01-04 20:39:45,209 | Read | 127.0.0.1 | 1424
Traceback (most recent call last):
  File "server-chatBot.py", line 32, in run
    userInput = self.socket.recv(2048).decode('utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
